# Generated by Django 2.2 on 2022-09-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220901_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categ',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
