# Generated by Django 2.2 on 2022-10-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
