# Generated by Django 2.2 on 2022-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20221002_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
